---
title: "Rename files to cancerType_TCGA Case_ID"
output: html_notebook
---

```{r}
library(plyr)
library(stringr)
```

```{r}

# get all the path of files
files <- list.files(path ="allFimoGFF/",
                    pattern = "fimo.gff", all.files = FALSE, 
                    full.names = TRUE, recursive =TRUE, 
                    ignore.case = FALSE, include.dirs =TRUE, no.. = TRUE)
head(files)
```

```{r}
# rename files to (cancerType + TCGA Case_ID)
plyr::a_ply(files,1, function(file) {
  file.uuid <- stringr::str_extract(file,
  "[:alnum:]{8}_[:alnum:]{4}_[:alnum:]{4}_[:alnum:]{4}_[:alnum:]{12}") # get stanfordUUID
  print(file.uuid)
  
  idx <- grep(file.uuid,gsub("-","_",table$stanfordUUID)) # use stanfordUUID to find the index
  
  barcode <- unique(table[idx,]$Case_ID) # get Case_ID and use it as the barcode, and give technical replicates the same barcode
  barcode <- stringr::str_extract(barcode, "[:alnum:]{4}-[:alnum:]{2}-[:alnum:]{4}-[:alnum:]{3}")
  
  cancerType <- strsplit(strsplit(file,split='//')[[1]][2], split='_')[[1]][1]
  cancerType_barcode <- paste0(c(cancerType, barcode), collapse='_')
  print(cancerType_barcode)
   
  filename <- stringr::str_extract(file,"[:alnum:]{4}_[:alnum:]{8}_[:alnum:]{4}_[:alnum:]{4}_[:alnum:]{4}_[:alnum:]{12}_[:alnum:]{4}_[:alnum:]{3}") # get the file name
  print (filename)

  to <- gsub(filename,cancerType_barcode,file) # change uuid in file names to new barcode
  print(to)
  file.rename(file, to) # rename files
})
```
